# Generated by Django 2.0.2 on 2018-02-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='private',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='token',
        ),
    ]
